In [1]:
#get the title of the movie/tv show that the user likes and if the user wants movies or tv shows
Title = "How the Grinch Stole Christmas"
Type = "Movie"

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("netflix_titles.csv")

In [4]:
df.head()

show_id     type                  title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson   
1      s2  TV Show          Blood & Water              NaN   
2      s3  TV Show              Ganglands  Julien Leclercq   
3      s4  TV Show  Jailbirds New Orleans              NaN   
4      s5  TV Show           Kota Factory              NaN   

                                                cast        country  \
0                                                NaN  United States   
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa   
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN   
3                                                NaN            NaN   
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India   

           date_added  release_year rating   duration  \
0  September 25, 2021          2020  PG-13     90 min   
1  September 24, 2021          2021  TV-MA  2 Seasons   
2  September 24, 2021          2021  TV-MA   1 Season   
3  September 24, 2021          2021  TV-MA   1 Season   
4  September 24, 2021          2021  TV-MA  2 Seasons   

                                           listed_in  \
0                                      Documentaries   
1    International TV Shows, TV Dramas, TV Mysteries   
2  Crime TV Shows, International TV Shows, TV Act...   
3                             Docuseries, Reality TV   
4  International TV Shows, Romantic TV Shows, TV ...   

                                         description  
0  As her father nears the end of his life, filmm...  
1  After crossing paths at a party, a Cape Town t...  
2  To protect his family from a powerful drug lor...  
3  Feuds, flirtations and toilet talk go down amo...  
4  In a city of coaching centers known to train I...

In [5]:
def missing_values_analysis(df):
    na_columns = [col for col in df.columns if df[col].isnull().sum() > 0]
    n_miss = df[na_columns].isnull().sum().sort_values(ascending=True)
    ratio = (df[na_columns].isnull().sum() / df.shape[0]*100).sort_values(ascending=True)
    missing_df = pd.concat([n_miss,np.round(ratio,2)],axis=1,keys=["missing values","ratio"])
    missing_df = pd.DataFrame(missing_df)
    return missing_df

def check_df(df, head=5, tail=5):
    print("Shape")
    print("rows: ", df.shape[0])
    print("columns: ",df.shape[1])
    print("------------------------------")
    print("Types")
    print(df.dtypes)
    print("")
    print("------------------------------")
    print(missing_values_analysis(df))
    print("------------------------------")
    print("duplicated values")
    print(df.duplicated().sum())
    print("------------------------------")
    print("quantiles")
    print(df.quantile([0,0.05,0.5,0.95,0.99,1]).T)

check_df(df)

Shape
rows:  8807
columns:  12
------------------------------
Types
show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

------------------------------
            missing values  ratio
duration                 3   0.03
rating                   4   0.05
date_added              10   0.11
cast                   825   9.37
country                831   9.44
director              2634  29.91
------------------------------
duplicated values
0
------------------------------
quantiles
                0.00    0.05    0.50    0.95    0.99    1.00
release_year  1925.0  1997.0  2017.0  2021.0  2021.0  2021.0


In [6]:
#unique values analysis
def check_class(df):
    unique_df = pd.DataFrame({"Variable": df.columns,
                             "Classes": [df[i].nunique() \
                                        for i in df.columns]})
    unique_df = unique_df.sort_values("Classes",ascending = False)
    unique_df = unique_df.reset_index(drop = True)
    return unique_df

check_class(df)

Variable  Classes
0        show_id     8807
1          title     8807
2    description     8775
3           cast     7692
4       director     4528
5     date_added     1767
6        country      748
7      listed_in      514
8       duration      220
9   release_year       74
10        rating       17
11          type        2

In [7]:
# #removing nulls 

# df = df.dropna(subset=["duration","rating","date_added","cast","country","director"])

In [8]:
check_df(df)

Shape
rows:  8807
columns:  12
------------------------------
Types
show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

------------------------------
            missing values  ratio
duration                 3   0.03
rating                   4   0.05
date_added              10   0.11
cast                   825   9.37
country                831   9.44
director              2634  29.91
------------------------------
duplicated values
0
------------------------------
quantiles
                0.00    0.05    0.50    0.95    0.99    1.00
release_year  1925.0  1997.0  2017.0  2021.0  2021.0  2021.0


In [9]:
df.head()


show_id     type                  title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson   
1      s2  TV Show          Blood & Water              NaN   
2      s3  TV Show              Ganglands  Julien Leclercq   
3      s4  TV Show  Jailbirds New Orleans              NaN   
4      s5  TV Show           Kota Factory              NaN   

                                                cast        country  \
0                                                NaN  United States   
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa   
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN   
3                                                NaN            NaN   
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India   

           date_added  release_year rating   duration  \
0  September 25, 2021          2020  PG-13     90 min   
1  September 24, 2021          2021  TV-MA  2 Seasons   
2  September 24, 2021          2021  TV-MA   1 Season   
3  September 24, 2021          2021  TV-MA   1 Season   
4  September 24, 2021          2021  TV-MA  2 Seasons   

                                           listed_in  \
0                                      Documentaries   
1    International TV Shows, TV Dramas, TV Mysteries   
2  Crime TV Shows, International TV Shows, TV Act...   
3                             Docuseries, Reality TV   
4  International TV Shows, Romantic TV Shows, TV ...   

                                         description  
0  As her father nears the end of his life, filmm...  
1  After crossing paths at a party, a Cape Town t...  
2  To protect his family from a powerful drug lor...  
3  Feuds, flirtations and toilet talk go down amo...  
4  In a city of coaching centers known to train I...

In [10]:
#get items according to user's type
df = df[df["type"] == Type]
df

show_id   type                             title  \
0         s1  Movie              Dick Johnson Is Dead   
6         s7  Movie  My Little Pony: A New Generation   
7         s8  Movie                           Sankofa   
9        s10  Movie                      The Starling   
12       s13  Movie                      Je Suis Karl   
...      ...    ...                               ...   
8801   s8802  Movie                           Zinzana   
8802   s8803  Movie                            Zodiac   
8804   s8805  Movie                        Zombieland   
8805   s8806  Movie                              Zoom   
8806   s8807  Movie                            Zubaan   

                           director  \
0                   Kirsten Johnson   
6     Robert Cullen, José Luis Ucha   
7                      Haile Gerima   
9                    Theodore Melfi   
12              Christian Schwochow   
...                             ...   
8801                Majid Al Ansari   
8802                  David Fincher   
8804                Ruben Fleischer   
8805                   Peter Hewitt   
8806                    Mozez Singh   

                                                   cast  \
0                                                   NaN   
6     Vanessa Hudgens, Kimiko Glenn, James Marsden, ...   
7     Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...   
9     Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...   
12    Luna Wedler, Jannis Niewöhner, Milan Peschel, ...   
...                                                 ...   
8801  Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...   
8802  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...   
8804  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...   
8805  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...   
8806  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...   

                                                country          date_added  \
0                                         United States  September 25, 2021   
6                                                   NaN  September 24, 2021   
7     United States, Ghana, Burkina Faso, United Kin...  September 24, 2021   
9                                         United States  September 24, 2021   
12                              Germany, Czech Republic  September 23, 2021   
...                                                 ...                 ...   
8801                       United Arab Emirates, Jordan       March 9, 2016   
8802                                      United States   November 20, 2019   
8804                                      United States    November 1, 2019   
8805                                      United States    January 11, 2020   
8806                                              India       March 2, 2019   

      release_year rating duration  \
0             2020  PG-13   90 min   
6             2021     PG   91 min   
7             1993  TV-MA  125 min   
9             2021  PG-13  104 min   
12            2021  TV-MA  127 min   
...            ...    ...      ...   
8801          2015  TV-MA   96 min   
8802          2007      R  158 min   
8804          2009      R   88 min   
8805          2006     PG   88 min   
8806          2015  TV-14  111 min   

                                             listed_in  \
0                                        Documentaries   
6                             Children & Family Movies   
7     Dramas, Independent Movies, International Movies   
9                                     Comedies, Dramas   
12                        Dramas, International Movies   
...                                                ...   
8801           Dramas, International Movies, Thrillers   
8802                    Cult Movies, Dramas, Thrillers   
8804                           Comedies, Horror Movies   
8805                Children & Family Movies, Comedies   
8806    Dramas, International Movies, Music & Musicals   

                                       

In [11]:
df = df.reset_index(drop=True)
df.head()

show_id   type                             title  \
0      s1  Movie              Dick Johnson Is Dead   
1      s7  Movie  My Little Pony: A New Generation   
2      s8  Movie                           Sankofa   
3     s10  Movie                      The Starling   
4     s13  Movie                      Je Suis Karl   

                        director  \
0                Kirsten Johnson   
1  Robert Cullen, José Luis Ucha   
2                   Haile Gerima   
3                 Theodore Melfi   
4            Christian Schwochow   

                                                cast  \
0                                                NaN   
1  Vanessa Hudgens, Kimiko Glenn, James Marsden, ...   
2  Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...   
3  Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...   
4  Luna Wedler, Jannis Niewöhner, Milan Peschel, ...   

                                             country          date_added  \
0                                      United States  September 25, 2021   
1                                                NaN  September 24, 2021   
2  United States, Ghana, Burkina Faso, United Kin...  September 24, 2021   
3                                      United States  September 24, 2021   
4                            Germany, Czech Republic  September 23, 2021   

   release_year rating duration  \
0          2020  PG-13   90 min   
1          2021     PG   91 min   
2          1993  TV-MA  125 min   
3          2021  PG-13  104 min   
4          2021  TV-MA  127 min   

                                          listed_in  \
0                                     Documentaries   
1                          Children & Family Movies   
2  Dramas, Independent Movies, International Movies   
3                                  Comedies, Dramas   
4                      Dramas, International Movies   

                                         description  
0  As her father nears the end of his life, filmm...  
1  Equestria's divided. But a bright-eyed hero be...  
2  On a photo shoot in Ghana, an American model s...  
3  A woman adjusting to life after a loss contend...  
4  After most of her family is murdered in a terr...

In [12]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
#list of important columns for recommendation

columns = ["director","cast","listed_in", "title","description"]

In [14]:
df[columns].head()

director  \
0                Kirsten Johnson   
1  Robert Cullen, José Luis Ucha   
2                   Haile Gerima   
3                 Theodore Melfi   
4            Christian Schwochow   

                                                cast  \
0                                                NaN   
1  Vanessa Hudgens, Kimiko Glenn, James Marsden, ...   
2  Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...   
3  Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...   
4  Luna Wedler, Jannis Niewöhner, Milan Peschel, ...   

                                          listed_in  \
0                                     Documentaries   
1                          Children & Family Movies   
2  Dramas, Independent Movies, International Movies   
3                                  Comedies, Dramas   
4                      Dramas, International Movies   

                              title  \
0              Dick Johnson Is Dead   
1  My Little Pony: A New Generation   
2                           Sankofa   
3                      The Starling   
4                      Je Suis Karl   

                                         description  
0  As her father nears the end of his life, filmm...  
1  Equestria's divided. But a bright-eyed hero be...  
2  On a photo shoot in Ghana, an American model s...  
3  A woman adjusting to life after a loss contend...  
4  After most of her family is murdered in a terr...

In [15]:
#combine important features into a single string

def get_important_features(data):
    important_features = []
    for i in range(0, data.shape[0]):
        curr = data["director"][i] , data["cast"][i] , data["listed_in"][i] , data["title"][i] , data["description"][i]
        curr = str(curr)
        curr = curr.replace(",","")
        important_features.append(curr)
    return important_features

In [16]:
#column to hold combined string

df["important_features"] = get_important_features(df)

df.head()

show_id   type                             title  \
0      s1  Movie              Dick Johnson Is Dead   
1      s7  Movie  My Little Pony: A New Generation   
2      s8  Movie                           Sankofa   
3     s10  Movie                      The Starling   
4     s13  Movie                      Je Suis Karl   

                        director  \
0                Kirsten Johnson   
1  Robert Cullen, José Luis Ucha   
2                   Haile Gerima   
3                 Theodore Melfi   
4            Christian Schwochow   

                                                cast  \
0                                                NaN   
1  Vanessa Hudgens, Kimiko Glenn, James Marsden, ...   
2  Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...   
3  Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...   
4  Luna Wedler, Jannis Niewöhner, Milan Peschel, ...   

                                             country          date_added  \
0                                      United States  September 25, 2021   
1                                                NaN  September 24, 2021   
2  United States, Ghana, Burkina Faso, United Kin...  September 24, 2021   
3                                      United States  September 24, 2021   
4                            Germany, Czech Republic  September 23, 2021   

   release_year rating duration  \
0          2020  PG-13   90 min   
1          2021     PG   91 min   
2          1993  TV-MA  125 min   
3          2021  PG-13  104 min   
4          2021  TV-MA  127 min   

                                          listed_in  \
0                                     Documentaries   
1                          Children & Family Movies   
2  Dramas, Independent Movies, International Movies   
3                                  Comedies, Dramas   
4                      Dramas, International Movies   

                                         description  \
0  As her father nears the end of his life, filmm...   
1  Equestria's divided. But a bright-eyed hero be...   
2  On a photo shoot in Ghana, an American model s...   
3  A woman adjusting to life after a loss contend...   
4  After most of her family is murdered in a terr...   

                                  important_features  
0  ('Kirsten Johnson' nan 'Documentaries' 'Dick J...  
1  ('Robert Cullen José Luis Ucha' 'Vanessa Hudge...  
2  ('Haile Gerima' 'Kofi Ghanaba Oyafunmike Ogunl...  
3  ('Theodore Melfi' "Melissa McCarthy Chris O'Do...  
4  ('Christian Schwochow' 'Luna Wedler Jannis Nie...

In [17]:
#converts text to a matrix of token counts
cm = CountVectorizer().fit_transform(df["important_features"])


In [18]:
#cosine similarity will get similarity matrix from token count matrix because it measures similarity between two non zero vectors
# each column and each row will be a recipe, and the value will be how similar it is one to the other
# so in the center diagonal line the values will be 1, because its the same recipe, and the similarity will be 100%
cs = cosine_similarity(cm)
print(cs)
print(cs.shape)

[[1.         0.07470439 0.15879769 ... 0.09002983 0.08421519 0.19492029]
 [0.07470439 1.         0.10454167 ... 0.0987826  0.09240266 0.10265789]
 [0.15879769 0.10454167 1.         ... 0.16798421 0.09820928 0.14547859]
 ...
 [0.09002983 0.0987826  0.16798421 ... 1.         0.13363062 0.06185896]
 [0.08421519 0.09240266 0.09820928 ... 0.13363062 1.         0.07715167]
 [0.19492029 0.10265789 0.14547859 ... 0.06185896 0.07715167 1.        ]]
(6131, 6131)


In [19]:
movie_id = df[df.title == Title].index.values[0]

movie_id

4700

In [20]:
#creates a list of enums for the similarity score, to connect recipe index (which is 0) and its similarity score
#then sorts list to get highest similarity score, and removes the one with 1 value, since it'll be the 
# recipe itself
scores = list(enumerate(cs[movie_id]))
sorted_scores = sorted(scores, key=lambda x:x[1], reverse=True)
sorted_scores = sorted_scores[1:]

In [21]:
sorted_scores

[(4414, 0.3895364838967174),
 (1089, 0.3567417733957578),
 (2717, 0.3484120230837249),
 (2623, 0.3391533656562534),
 (704, 0.3364932981888754),
 (4734, 0.33447293779724757),
 (551, 0.32968283283670624),
 (4144, 0.32901761256080025),
 (1866, 0.3251142977670293),
 (264, 0.3244075671494598),
 (4230, 0.3215367596812404),
 (989, 0.32117337275819235),
 (5297, 0.3194752595165698),
 (4702, 0.3172489239642411),
 (4540, 0.3156365013686852),
 (4086, 0.31506849315068497),
 (4915, 0.31469724952594685),
 (5789, 0.31469724952594685),
 (3385, 0.31073885630742243),
 (2558, 0.3106219624777934),
 (3334, 0.30838304975156794),
 (1820, 0.3083264378478646),
 (334, 0.3054599216971784),
 (360, 0.30486052019825927),
 (2189, 0.3040818202797687),
 (4288, 0.303455492487535),
 (6122, 0.30345549248753495),
 (5572, 0.3025421556003685),
 (3600, 0.3009629499329072),
 (4442, 0.29995848612724885),
 (4984, 0.2997116662151875),
 (5156, 0.29971166621518747),
 (5720, 0.29932665394319524),
 (263, 0.2972757474636472),
 (1781, 

In [29]:
#print 7 most similar movies

print("The recommended movies are: ")
j = 0
for item in sorted_scores:
    movie_title = df.loc[item[0]].title
    print("#",j+1, movie_title)
    j = j+1
    if j > 6:
        break

The recommended movies are: 
# 1 Dr. Seuss' The Grinch
# 2 The App That Stole Christmas
# 3 Prince of Peoria: A Christmas Moose Miracle
# 4 LEGO Marvel Super Heroes: Guardians of the Galaxy
# 5 Shiva: The Secret World Of Vedas City
# 6 Igor
# 7 Little Singham Future mein Satakli
